//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./v1/dhll.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace dhll.v1 {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class dhllLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, ASSIGN=2, INT=3, FALSE=4, TRUE=5, PUBLIC=6, PRIVATE=7, PROP=8, 
		FIRSTCHAR=9, ID=10, WORD=11, QUOTE=12, STRING=13, OBRACE=14, CBRACE=15, 
		EOS=16, WS=17;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "ASSIGN", "INT", "FALSE", "TRUE", "PUBLIC", "PRIVATE", "PROP", 
		"FIRSTCHAR", "ID", "WORD", "QUOTE", "STRING", "OBRACE", "CBRACE", "EOS", 
		"WS"
	};


	public dhllLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public dhllLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'typedef'", "'='", null, "'false'", "'true'", "'public'", "'private'", 
		"'prop'", null, null, null, "'\"'", null, "'{'", "'}'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "ASSIGN", "INT", "FALSE", "TRUE", "PUBLIC", "PRIVATE", "PROP", 
		"FIRSTCHAR", "ID", "WORD", "QUOTE", "STRING", "OBRACE", "CBRACE", "EOS", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "dhll.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static dhllLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,17,115,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,2,4,
		2,47,8,2,11,2,12,2,48,1,3,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,
		7,1,7,1,8,1,8,1,9,1,9,4,9,86,8,9,11,9,12,9,87,1,10,4,10,91,8,10,11,10,
		12,10,92,1,11,1,11,1,12,1,12,5,12,99,8,12,10,12,12,12,102,9,12,1,12,1,
		12,1,13,1,13,1,14,1,14,1,15,1,15,1,16,1,16,1,16,1,16,1,100,0,17,1,1,3,
		2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,14,29,15,
		31,16,33,17,1,0,5,1,0,48,57,3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,
		95,97,122,2,0,65,90,97,122,3,0,9,10,13,13,32,32,118,0,1,1,0,0,0,0,3,1,
		0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,
		15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,
		0,0,0,0,27,1,0,0,0,0,29,1,0,0,0,0,31,1,0,0,0,0,33,1,0,0,0,1,35,1,0,0,0,
		3,43,1,0,0,0,5,46,1,0,0,0,7,50,1,0,0,0,9,56,1,0,0,0,11,61,1,0,0,0,13,68,
		1,0,0,0,15,76,1,0,0,0,17,81,1,0,0,0,19,83,1,0,0,0,21,90,1,0,0,0,23,94,
		1,0,0,0,25,96,1,0,0,0,27,105,1,0,0,0,29,107,1,0,0,0,31,109,1,0,0,0,33,
		111,1,0,0,0,35,36,5,116,0,0,36,37,5,121,0,0,37,38,5,112,0,0,38,39,5,101,
		0,0,39,40,5,100,0,0,40,41,5,101,0,0,41,42,5,102,0,0,42,2,1,0,0,0,43,44,
		5,61,0,0,44,4,1,0,0,0,45,47,7,0,0,0,46,45,1,0,0,0,47,48,1,0,0,0,48,46,
		1,0,0,0,48,49,1,0,0,0,49,6,1,0,0,0,50,51,5,102,0,0,51,52,5,97,0,0,52,53,
		5,108,0,0,53,54,5,115,0,0,54,55,5,101,0,0,55,8,1,0,0,0,56,57,5,116,0,0,
		57,58,5,114,0,0,58,59,5,117,0,0,59,60,5,101,0,0,60,10,1,0,0,0,61,62,5,
		112,0,0,62,63,5,117,0,0,63,64,5,98,0,0,64,65,5,108,0,0,65,66,5,105,0,0,
		66,67,5,99,0,0,67,12,1,0,0,0,68,69,5,112,0,0,69,70,5,114,0,0,70,71,5,105,
		0,0,71,72,5,118,0,0,72,73,5,97,0,0,73,74,5,116,0,0,74,75,5,101,0,0,75,
		14,1,0,0,0,76,77,5,112,0,0,77,78,5,114,0,0,78,79,5,111,0,0,79,80,5,112,
		0,0,80,16,1,0,0,0,81,82,7,1,0,0,82,18,1,0,0,0,83,85,3,17,8,0,84,86,7,2,
		0,0,85,84,1,0,0,0,86,87,1,0,0,0,87,85,1,0,0,0,87,88,1,0,0,0,88,20,1,0,
		0,0,89,91,7,3,0,0,90,89,1,0,0,0,91,92,1,0,0,0,92,90,1,0,0,0,92,93,1,0,
		0,0,93,22,1,0,0,0,94,95,5,34,0,0,95,24,1,0,0,0,96,100,3,23,11,0,97,99,
		9,0,0,0,98,97,1,0,0,0,99,102,1,0,0,0,100,101,1,0,0,0,100,98,1,0,0,0,101,
		103,1,0,0,0,102,100,1,0,0,0,103,104,3,23,11,0,104,26,1,0,0,0,105,106,5,
		123,0,0,106,28,1,0,0,0,107,108,5,125,0,0,108,30,1,0,0,0,109,110,5,59,0,
		0,110,32,1,0,0,0,111,112,7,4,0,0,112,113,1,0,0,0,113,114,6,16,0,0,114,
		34,1,0,0,0,5,0,48,87,92,100,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace dhll.v1
