//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./v1/dhll.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace dhll.v1 {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class dhllLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, ASSIGN=2, INT=3, FALSE=4, TRUE=5, PUBLIC=6, PRIVATE=7, PROP=8, 
		ID=9, ARRAY=10, WORD=11, OBRACE=12, CBRACE=13, EOS=14, COMMENT=15, STRING=16, 
		LF=17, WS=18;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "ASSIGN", "INT", "FALSE", "TRUE", "PUBLIC", "PRIVATE", "PROP", 
		"ID", "FIRSTCHAR", "ARRAY", "OSQUARE", "CSQUARE", "WORD", "SLASH", "QUOTE", 
		"OBRACE", "CBRACE", "EOS", "COMMENT", "STRING", "LF", "WS"
	};


	public dhllLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public dhllLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'typedef'", "'='", null, "'false'", "'true'", "'public'", "'private'", 
		"'prop'", null, null, null, "'{'", "'}'", "';'", null, null, "'\\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "ASSIGN", "INT", "FALSE", "TRUE", "PUBLIC", "PRIVATE", "PROP", 
		"ID", "ARRAY", "WORD", "OBRACE", "CBRACE", "EOS", "COMMENT", "STRING", 
		"LF", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "dhll.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static dhllLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,18,153,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,2,22,7,22,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,2,4,2,59,8,2,
		11,2,12,2,60,1,3,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,
		5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,8,
		1,8,5,8,96,8,8,10,8,12,8,99,9,8,1,9,1,9,1,10,1,10,1,10,1,11,1,11,1,12,
		1,12,1,13,4,13,111,8,13,11,13,12,13,112,1,14,1,14,1,15,1,15,1,16,1,16,
		1,17,1,17,1,18,1,18,1,19,1,19,1,19,5,19,128,8,19,10,19,12,19,131,9,19,
		1,19,1,19,1,19,1,19,1,20,1,20,5,20,139,8,20,10,20,12,20,142,9,20,1,20,
		1,20,1,21,1,21,1,21,1,21,1,22,1,22,1,22,1,22,2,129,140,0,23,1,1,3,2,5,
		3,7,4,9,5,11,6,13,7,15,8,17,9,19,0,21,10,23,0,25,0,27,11,29,0,31,0,33,
		12,35,13,37,14,39,15,41,16,43,17,45,18,1,0,5,1,0,48,57,4,0,48,57,65,90,
		95,95,97,122,3,0,65,90,95,95,97,122,2,0,65,90,97,122,3,0,9,10,13,13,32,
		32,152,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,
		1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,21,1,0,0,0,0,27,1,0,0,
		0,0,33,1,0,0,0,0,35,1,0,0,0,0,37,1,0,0,0,0,39,1,0,0,0,0,41,1,0,0,0,0,43,
		1,0,0,0,0,45,1,0,0,0,1,47,1,0,0,0,3,55,1,0,0,0,5,58,1,0,0,0,7,62,1,0,0,
		0,9,68,1,0,0,0,11,73,1,0,0,0,13,80,1,0,0,0,15,88,1,0,0,0,17,93,1,0,0,0,
		19,100,1,0,0,0,21,102,1,0,0,0,23,105,1,0,0,0,25,107,1,0,0,0,27,110,1,0,
		0,0,29,114,1,0,0,0,31,116,1,0,0,0,33,118,1,0,0,0,35,120,1,0,0,0,37,122,
		1,0,0,0,39,124,1,0,0,0,41,136,1,0,0,0,43,145,1,0,0,0,45,149,1,0,0,0,47,
		48,5,116,0,0,48,49,5,121,0,0,49,50,5,112,0,0,50,51,5,101,0,0,51,52,5,100,
		0,0,52,53,5,101,0,0,53,54,5,102,0,0,54,2,1,0,0,0,55,56,5,61,0,0,56,4,1,
		0,0,0,57,59,7,0,0,0,58,57,1,0,0,0,59,60,1,0,0,0,60,58,1,0,0,0,60,61,1,
		0,0,0,61,6,1,0,0,0,62,63,5,102,0,0,63,64,5,97,0,0,64,65,5,108,0,0,65,66,
		5,115,0,0,66,67,5,101,0,0,67,8,1,0,0,0,68,69,5,116,0,0,69,70,5,114,0,0,
		70,71,5,117,0,0,71,72,5,101,0,0,72,10,1,0,0,0,73,74,5,112,0,0,74,75,5,
		117,0,0,75,76,5,98,0,0,76,77,5,108,0,0,77,78,5,105,0,0,78,79,5,99,0,0,
		79,12,1,0,0,0,80,81,5,112,0,0,81,82,5,114,0,0,82,83,5,105,0,0,83,84,5,
		118,0,0,84,85,5,97,0,0,85,86,5,116,0,0,86,87,5,101,0,0,87,14,1,0,0,0,88,
		89,5,112,0,0,89,90,5,114,0,0,90,91,5,111,0,0,91,92,5,112,0,0,92,16,1,0,
		0,0,93,97,3,19,9,0,94,96,7,1,0,0,95,94,1,0,0,0,96,99,1,0,0,0,97,95,1,0,
		0,0,97,98,1,0,0,0,98,18,1,0,0,0,99,97,1,0,0,0,100,101,7,2,0,0,101,20,1,
		0,0,0,102,103,3,23,11,0,103,104,3,25,12,0,104,22,1,0,0,0,105,106,5,91,
		0,0,106,24,1,0,0,0,107,108,5,93,0,0,108,26,1,0,0,0,109,111,7,3,0,0,110,
		109,1,0,0,0,111,112,1,0,0,0,112,110,1,0,0,0,112,113,1,0,0,0,113,28,1,0,
		0,0,114,115,5,47,0,0,115,30,1,0,0,0,116,117,5,34,0,0,117,32,1,0,0,0,118,
		119,5,123,0,0,119,34,1,0,0,0,120,121,5,125,0,0,121,36,1,0,0,0,122,123,
		5,59,0,0,123,38,1,0,0,0,124,125,3,29,14,0,125,129,3,29,14,0,126,128,9,
		0,0,0,127,126,1,0,0,0,128,131,1,0,0,0,129,130,1,0,0,0,129,127,1,0,0,0,
		130,132,1,0,0,0,131,129,1,0,0,0,132,133,5,10,0,0,133,134,1,0,0,0,134,135,
		6,19,0,0,135,40,1,0,0,0,136,140,3,31,15,0,137,139,9,0,0,0,138,137,1,0,
		0,0,139,142,1,0,0,0,140,141,1,0,0,0,140,138,1,0,0,0,141,143,1,0,0,0,142,
		140,1,0,0,0,143,144,3,31,15,0,144,42,1,0,0,0,145,146,5,10,0,0,146,147,
		1,0,0,0,147,148,6,21,1,0,148,44,1,0,0,0,149,150,7,4,0,0,150,151,1,0,0,
		0,151,152,6,22,1,0,152,46,1,0,0,0,6,0,60,97,112,129,140,2,0,1,0,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace dhll.v1
