//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./v1/templateLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace dhll.v1 {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class templateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SEA_WS=1, TAG_OPEN=2, HTML_TEXT=3, EXP_OPEN=4, TAG_CLOSE=5, TAG_SLASH_CLOSE=6, 
		TAG_SLASH=7, TAG_EQUALS=8, TAG_NAME=9, TAG_WHITESPACE=10, TAG_DBL_QUOTE=11, 
		TAG_DQ_STR=12, TAG_EXP_OPEN=13, EXP_CLOSE=14, PLUS=15, MINUS=16, MULT=17, 
		DIVIDE=18, ID=19, OPEN_PAREN=20, CLOSE_PAREN=21, COMMA=22, INT=23, REAL=24, 
		EXP_DBL_QUOTE=25, EXP_DQ_STR=26, EXP_WS=27, ANY=28;
	public const int
		TAG=1, EXPRESSION=2;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "TAG", "EXPRESSION"
	};

	public static readonly string[] ruleNames = {
		"SEA_WS", "TAG_OPEN", "ESCAPED_CHARS", "HTML_TEXT", "EXP_OPEN", "TAG_CLOSE", 
		"TAG_SLASH_CLOSE", "TAG_SLASH", "TAG_EQUALS", "TAG_NAME", "TAG_WHITESPACE", 
		"HEXDIGIT", "DIGIT", "TAG_NameChar", "TAG_NameStartChar", "TAG_DBL_QUOTE", 
		"TAG_DQ_STR", "TAG_EXP_OPEN", "EXP_CLOSE", "PLUS", "MINUS", "MULT", "DIVIDE", 
		"ID", "OPEN_PAREN", "CLOSE_PAREN", "COMMA", "INT", "REAL", "EXP_DBL_QUOTE", 
		"EXP_DQ_STR", "EXP_WS", "ANY"
	};


	public templateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public templateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "'<'", null, null, "'>'", "'/>'", null, "'='", null, null, 
		null, null, null, "'}'", "'+'", "'-'", "'*'", null, null, "'('", "')'", 
		"','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SEA_WS", "TAG_OPEN", "HTML_TEXT", "EXP_OPEN", "TAG_CLOSE", "TAG_SLASH_CLOSE", 
		"TAG_SLASH", "TAG_EQUALS", "TAG_NAME", "TAG_WHITESPACE", "TAG_DBL_QUOTE", 
		"TAG_DQ_STR", "TAG_EXP_OPEN", "EXP_CLOSE", "PLUS", "MINUS", "MULT", "DIVIDE", 
		"ID", "OPEN_PAREN", "CLOSE_PAREN", "COMMA", "INT", "REAL", "EXP_DBL_QUOTE", 
		"EXP_DQ_STR", "EXP_WS", "ANY"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "templateLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static templateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,28,205,6,-1,6,-1,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,
		7,5,2,6,7,6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,
		7,13,2,14,7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,
		7,20,2,21,7,21,2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,
		7,27,2,28,7,28,2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,1,0,1,0,3,0,72,
		8,0,1,0,4,0,75,8,0,11,0,12,0,76,1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,3,1,3,4,
		3,88,8,3,11,3,12,3,89,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,
		1,6,1,7,1,7,1,8,1,8,1,9,1,9,5,9,111,8,9,10,9,12,9,114,9,9,1,10,1,10,1,
		10,1,10,1,11,1,11,1,12,1,12,1,13,1,13,1,13,1,13,3,13,128,8,13,1,14,3,14,
		131,8,14,1,15,1,15,1,16,1,16,5,16,137,8,16,10,16,12,16,140,9,16,1,16,1,
		16,1,17,1,17,1,17,1,17,1,18,1,18,1,18,1,18,1,19,1,19,1,20,1,20,1,21,1,
		21,1,22,1,22,1,23,1,23,5,23,162,8,23,10,23,12,23,165,9,23,1,24,1,24,1,
		25,1,25,1,26,1,26,1,27,4,27,174,8,27,11,27,12,27,175,1,28,4,28,179,8,28,
		11,28,12,28,180,1,28,1,28,4,28,185,8,28,11,28,12,28,186,1,29,1,29,1,30,
		1,30,5,30,193,8,30,10,30,12,30,196,9,30,1,30,1,30,1,31,1,31,1,31,1,31,
		1,32,1,32,1,180,0,33,3,1,5,2,7,0,9,3,11,4,13,5,15,6,17,7,19,8,21,9,23,
		10,25,0,27,0,29,0,31,0,33,11,35,12,37,13,39,14,41,15,43,16,45,17,47,18,
		49,19,51,20,53,21,55,22,57,23,59,24,61,25,63,26,65,27,67,28,3,0,1,2,12,
		2,0,9,9,32,32,3,0,34,34,123,123,125,125,2,0,60,60,123,123,3,0,9,10,13,
		13,32,32,3,0,48,57,65,70,97,102,1,0,48,57,2,0,45,46,95,95,3,0,183,183,
		768,879,8255,8256,8,0,58,58,65,90,97,122,8304,8591,11264,12271,12289,55295,
		63744,64975,65008,65533,1,0,34,34,3,0,65,90,95,95,97,122,4,0,48,57,65,
		90,95,95,97,122,212,0,3,1,0,0,0,0,5,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,1,
		13,1,0,0,0,1,15,1,0,0,0,1,17,1,0,0,0,1,19,1,0,0,0,1,21,1,0,0,0,1,23,1,
		0,0,0,1,33,1,0,0,0,1,35,1,0,0,0,1,37,1,0,0,0,2,39,1,0,0,0,2,41,1,0,0,0,
		2,43,1,0,0,0,2,45,1,0,0,0,2,47,1,0,0,0,2,49,1,0,0,0,2,51,1,0,0,0,2,53,
		1,0,0,0,2,55,1,0,0,0,2,57,1,0,0,0,2,59,1,0,0,0,2,61,1,0,0,0,2,63,1,0,0,
		0,2,65,1,0,0,0,2,67,1,0,0,0,3,74,1,0,0,0,5,78,1,0,0,0,7,82,1,0,0,0,9,87,
		1,0,0,0,11,91,1,0,0,0,13,95,1,0,0,0,15,99,1,0,0,0,17,104,1,0,0,0,19,106,
		1,0,0,0,21,108,1,0,0,0,23,115,1,0,0,0,25,119,1,0,0,0,27,121,1,0,0,0,29,
		127,1,0,0,0,31,130,1,0,0,0,33,132,1,0,0,0,35,134,1,0,0,0,37,143,1,0,0,
		0,39,147,1,0,0,0,41,151,1,0,0,0,43,153,1,0,0,0,45,155,1,0,0,0,47,157,1,
		0,0,0,49,159,1,0,0,0,51,166,1,0,0,0,53,168,1,0,0,0,55,170,1,0,0,0,57,173,
		1,0,0,0,59,178,1,0,0,0,61,188,1,0,0,0,63,190,1,0,0,0,65,199,1,0,0,0,67,
		203,1,0,0,0,69,75,7,0,0,0,70,72,5,13,0,0,71,70,1,0,0,0,71,72,1,0,0,0,72,
		73,1,0,0,0,73,75,5,10,0,0,74,69,1,0,0,0,74,71,1,0,0,0,75,76,1,0,0,0,76,
		74,1,0,0,0,76,77,1,0,0,0,77,4,1,0,0,0,78,79,5,60,0,0,79,80,1,0,0,0,80,
		81,6,1,0,0,81,6,1,0,0,0,82,83,5,92,0,0,83,84,7,1,0,0,84,8,1,0,0,0,85,88,
		3,7,2,0,86,88,8,2,0,0,87,85,1,0,0,0,87,86,1,0,0,0,88,89,1,0,0,0,89,87,
		1,0,0,0,89,90,1,0,0,0,90,10,1,0,0,0,91,92,5,123,0,0,92,93,1,0,0,0,93,94,
		6,4,1,0,94,12,1,0,0,0,95,96,5,62,0,0,96,97,1,0,0,0,97,98,6,5,2,0,98,14,
		1,0,0,0,99,100,5,47,0,0,100,101,5,62,0,0,101,102,1,0,0,0,102,103,6,6,2,
		0,103,16,1,0,0,0,104,105,5,47,0,0,105,18,1,0,0,0,106,107,5,61,0,0,107,
		20,1,0,0,0,108,112,3,31,14,0,109,111,3,29,13,0,110,109,1,0,0,0,111,114,
		1,0,0,0,112,110,1,0,0,0,112,113,1,0,0,0,113,22,1,0,0,0,114,112,1,0,0,0,
		115,116,7,3,0,0,116,117,1,0,0,0,117,118,6,10,3,0,118,24,1,0,0,0,119,120,
		7,4,0,0,120,26,1,0,0,0,121,122,7,5,0,0,122,28,1,0,0,0,123,128,3,31,14,
		0,124,128,7,6,0,0,125,128,3,27,12,0,126,128,7,7,0,0,127,123,1,0,0,0,127,
		124,1,0,0,0,127,125,1,0,0,0,127,126,1,0,0,0,128,30,1,0,0,0,129,131,7,8,
		0,0,130,129,1,0,0,0,131,32,1,0,0,0,132,133,5,34,0,0,133,34,1,0,0,0,134,
		138,3,33,15,0,135,137,8,9,0,0,136,135,1,0,0,0,137,140,1,0,0,0,138,136,
		1,0,0,0,138,139,1,0,0,0,139,141,1,0,0,0,140,138,1,0,0,0,141,142,3,33,15,
		0,142,36,1,0,0,0,143,144,5,123,0,0,144,145,1,0,0,0,145,146,6,17,1,0,146,
		38,1,0,0,0,147,148,5,125,0,0,148,149,1,0,0,0,149,150,6,18,2,0,150,40,1,
		0,0,0,151,152,5,43,0,0,152,42,1,0,0,0,153,154,5,45,0,0,154,44,1,0,0,0,
		155,156,5,42,0,0,156,46,1,0,0,0,157,158,5,47,0,0,158,48,1,0,0,0,159,163,
		7,10,0,0,160,162,7,11,0,0,161,160,1,0,0,0,162,165,1,0,0,0,163,161,1,0,
		0,0,163,164,1,0,0,0,164,50,1,0,0,0,165,163,1,0,0,0,166,167,5,40,0,0,167,
		52,1,0,0,0,168,169,5,41,0,0,169,54,1,0,0,0,170,171,5,44,0,0,171,56,1,0,
		0,0,172,174,3,27,12,0,173,172,1,0,0,0,174,175,1,0,0,0,175,173,1,0,0,0,
		175,176,1,0,0,0,176,58,1,0,0,0,177,179,3,27,12,0,178,177,1,0,0,0,179,180,
		1,0,0,0,180,181,1,0,0,0,180,178,1,0,0,0,181,182,1,0,0,0,182,184,5,46,0,
		0,183,185,3,27,12,0,184,183,1,0,0,0,185,186,1,0,0,0,186,184,1,0,0,0,186,
		187,1,0,0,0,187,60,1,0,0,0,188,189,5,34,0,0,189,62,1,0,0,0,190,194,3,33,
		15,0,191,193,8,9,0,0,192,191,1,0,0,0,193,196,1,0,0,0,194,192,1,0,0,0,194,
		195,1,0,0,0,195,197,1,0,0,0,196,194,1,0,0,0,197,198,3,33,15,0,198,64,1,
		0,0,0,199,200,7,3,0,0,200,201,1,0,0,0,201,202,6,31,4,0,202,66,1,0,0,0,
		203,204,9,0,0,0,204,68,1,0,0,0,17,0,1,2,71,74,76,87,89,112,127,130,138,
		163,175,180,186,194,5,5,1,0,5,2,0,4,0,0,0,1,0,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace dhll.v1
