//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./v1/templateParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace dhll.v1 {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="templateParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ItemplateParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.templates"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplates([NotNull] templateParser.TemplatesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.templates"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplates([NotNull] templateParser.TemplatesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.htmlElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlElements([NotNull] templateParser.HtmlElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.htmlElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlElements([NotNull] templateParser.HtmlElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.htmlMisc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlMisc([NotNull] templateParser.HtmlMiscContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.htmlMisc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlMisc([NotNull] templateParser.HtmlMiscContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.entityName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityName([NotNull] templateParser.EntityNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.entityName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityName([NotNull] templateParser.EntityNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.htmlElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlElement([NotNull] templateParser.HtmlElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.htmlElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlElement([NotNull] templateParser.HtmlElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.htmlContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlContent([NotNull] templateParser.HtmlContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.htmlContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlContent([NotNull] templateParser.HtmlContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttribute([NotNull] templateParser.HtmlAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttribute([NotNull] templateParser.HtmlAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="templateParser.htmlChardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlChardata([NotNull] templateParser.HtmlChardataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="templateParser.htmlChardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlChardata([NotNull] templateParser.HtmlChardataContext context);
}
} // namespace dhll.v1
