//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./v1/templateParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace dhll.v1 {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class templateParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SEA_WS=1, TAG_OPEN=2, HTML_TEXT=3, EXP_OPEN=4, TAG_CLOSE=5, TAG_SLASH_CLOSE=6, 
		TAG_SLASH=7, TAG_EQUALS=8, TAG_NAME=9, TAG_WHITESPACE=10, TAG_DBL_QUOTE=11, 
		TAG_DQ_STR=12, TAG_EXP_OPEN=13, EXP_CLOSE=14, PLUS=15, MINUS=16, MULT=17, 
		DIVIDE=18, ID=19, OPEN_PAREN=20, CLOSE_PAREN=21, COMMA=22, INT=23, REAL=24, 
		EXP_DBL_QUOTE=25, EXP_DQ_STR=26, EXP_WS=27, ANY=28;
	public const int
		RULE_templates = 0, RULE_htmlElements = 1, RULE_htmlMisc = 2, RULE_entityName = 3, 
		RULE_htmlElement = 4, RULE_htmlContent = 5, RULE_expression = 6, RULE_htmlAttribute = 7, 
		RULE_htmlChardata = 8, RULE_attrValue = 9, RULE_tag_expression = 10, RULE_expr = 11, 
		RULE_additiveExpr = 12, RULE_multiplicativeExpr = 13, RULE_unaryExpr = 14, 
		RULE_primaryExpr = 15, RULE_argList = 16, RULE_number = 17;
	public static readonly string[] ruleNames = {
		"templates", "htmlElements", "htmlMisc", "entityName", "htmlElement", 
		"htmlContent", "expression", "htmlAttribute", "htmlChardata", "attrValue", 
		"tag_expression", "expr", "additiveExpr", "multiplicativeExpr", "unaryExpr", 
		"primaryExpr", "argList", "number"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "'<'", null, null, "'>'", "'/>'", null, "'='", null, null, 
		null, null, null, "'}'", "'+'", "'-'", "'*'", null, null, "'('", "')'", 
		"','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SEA_WS", "TAG_OPEN", "HTML_TEXT", "EXP_OPEN", "TAG_CLOSE", "TAG_SLASH_CLOSE", 
		"TAG_SLASH", "TAG_EQUALS", "TAG_NAME", "TAG_WHITESPACE", "TAG_DBL_QUOTE", 
		"TAG_DQ_STR", "TAG_EXP_OPEN", "EXP_CLOSE", "PLUS", "MINUS", "MULT", "DIVIDE", 
		"ID", "OPEN_PAREN", "CLOSE_PAREN", "COMMA", "INT", "REAL", "EXP_DBL_QUOTE", 
		"EXP_DQ_STR", "EXP_WS", "ANY"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "templateParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static templateParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public templateParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public templateParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class TemplatesContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(templateParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public HtmlElementsContext[] htmlElements() {
			return GetRuleContexts<HtmlElementsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlElementsContext htmlElements(int i) {
			return GetRuleContext<HtmlElementsContext>(i);
		}
		public TemplatesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_templates; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterTemplates(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitTemplates(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemplates(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TemplatesContext templates() {
		TemplatesContext _localctx = new TemplatesContext(Context, State);
		EnterRule(_localctx, 0, RULE_templates);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SEA_WS || _la==TAG_OPEN) {
				{
				{
				State = 36;
				htmlElements();
				}
				}
				State = 41;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 42;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HtmlElementsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public HtmlElementContext htmlElement() {
			return GetRuleContext<HtmlElementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlMiscContext[] htmlMisc() {
			return GetRuleContexts<HtmlMiscContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlMiscContext htmlMisc(int i) {
			return GetRuleContext<HtmlMiscContext>(i);
		}
		public HtmlElementsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_htmlElements; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterHtmlElements(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitHtmlElements(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHtmlElements(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HtmlElementsContext htmlElements() {
		HtmlElementsContext _localctx = new HtmlElementsContext(Context, State);
		EnterRule(_localctx, 2, RULE_htmlElements);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SEA_WS) {
				{
				{
				State = 44;
				htmlMisc();
				}
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 50;
			htmlElement();
			State = 54;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 51;
					htmlMisc();
					}
					} 
				}
				State = 56;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HtmlMiscContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEA_WS() { return GetToken(templateParser.SEA_WS, 0); }
		public HtmlMiscContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_htmlMisc; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterHtmlMisc(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitHtmlMisc(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHtmlMisc(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HtmlMiscContext htmlMisc() {
		HtmlMiscContext _localctx = new HtmlMiscContext(Context, State);
		EnterRule(_localctx, 4, RULE_htmlMisc);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57;
			Match(SEA_WS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_NAME() { return GetToken(templateParser.TAG_NAME, 0); }
		public EntityNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterEntityName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitEntityName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntityName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EntityNameContext entityName() {
		EntityNameContext _localctx = new EntityNameContext(Context, State);
		EnterRule(_localctx, 6, RULE_entityName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			Match(TAG_NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HtmlElementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TAG_OPEN() { return GetTokens(templateParser.TAG_OPEN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_OPEN(int i) {
			return GetToken(templateParser.TAG_OPEN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EntityNameContext entityName() {
			return GetRuleContext<EntityNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TAG_CLOSE() { return GetTokens(templateParser.TAG_CLOSE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_CLOSE(int i) {
			return GetToken(templateParser.TAG_CLOSE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_SLASH_CLOSE() { return GetToken(templateParser.TAG_SLASH_CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public HtmlAttributeContext[] htmlAttribute() {
			return GetRuleContexts<HtmlAttributeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlAttributeContext htmlAttribute(int i) {
			return GetRuleContext<HtmlAttributeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlContentContext htmlContent() {
			return GetRuleContext<HtmlContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_SLASH() { return GetToken(templateParser.TAG_SLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_NAME() { return GetToken(templateParser.TAG_NAME, 0); }
		public HtmlElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_htmlElement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterHtmlElement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitHtmlElement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHtmlElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HtmlElementContext htmlElement() {
		HtmlElementContext _localctx = new HtmlElementContext(Context, State);
		EnterRule(_localctx, 8, RULE_htmlElement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			Match(TAG_OPEN);
			State = 62;
			entityName();
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==TAG_NAME) {
				{
				{
				State = 63;
				htmlAttribute();
				}
				}
				State = 68;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 79;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TAG_CLOSE:
				{
				State = 69;
				Match(TAG_CLOSE);
				State = 76;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
				case 1:
					{
					State = 70;
					htmlContent();
					State = 71;
					Match(TAG_OPEN);
					State = 72;
					Match(TAG_SLASH);
					State = 73;
					Match(TAG_NAME);
					State = 74;
					Match(TAG_CLOSE);
					}
					break;
				}
				}
				break;
			case TAG_SLASH_CLOSE:
				{
				State = 78;
				Match(TAG_SLASH_CLOSE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HtmlContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public HtmlChardataContext[] htmlChardata() {
			return GetRuleContexts<HtmlChardataContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlChardataContext htmlChardata(int i) {
			return GetRuleContext<HtmlChardataContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlElementContext[] htmlElement() {
			return GetRuleContexts<HtmlElementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public HtmlElementContext htmlElement(int i) {
			return GetRuleContext<HtmlElementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public HtmlContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_htmlContent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterHtmlContent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitHtmlContent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHtmlContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HtmlContentContext htmlContent() {
		HtmlContentContext _localctx = new HtmlContentContext(Context, State);
		EnterRule(_localctx, 10, RULE_htmlContent);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SEA_WS || _la==HTML_TEXT) {
				{
				State = 81;
				htmlChardata();
				}
			}

			State = 93;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 86;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case TAG_OPEN:
						{
						State = 84;
						htmlElement();
						}
						break;
					case EXP_OPEN:
						{
						State = 85;
						expression();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 89;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==SEA_WS || _la==HTML_TEXT) {
						{
						State = 88;
						htmlChardata();
						}
					}

					}
					} 
				}
				State = 95;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXP_OPEN() { return GetToken(templateParser.EXP_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXP_CLOSE() { return GetToken(templateParser.EXP_CLOSE, 0); }
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 12, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			Match(EXP_OPEN);
			State = 97;
			expr();
			State = 98;
			Match(EXP_CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HtmlAttributeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EntityNameContext entityName() {
			return GetRuleContext<EntityNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_EQUALS() { return GetToken(templateParser.TAG_EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AttrValueContext attrValue() {
			return GetRuleContext<AttrValueContext>(0);
		}
		public HtmlAttributeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_htmlAttribute; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterHtmlAttribute(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitHtmlAttribute(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHtmlAttribute(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HtmlAttributeContext htmlAttribute() {
		HtmlAttributeContext _localctx = new HtmlAttributeContext(Context, State);
		EnterRule(_localctx, 14, RULE_htmlAttribute);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			entityName();
			State = 103;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TAG_EQUALS) {
				{
				State = 101;
				Match(TAG_EQUALS);
				State = 102;
				attrValue();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HtmlChardataContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HTML_TEXT() { return GetToken(templateParser.HTML_TEXT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEA_WS() { return GetToken(templateParser.SEA_WS, 0); }
		public HtmlChardataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_htmlChardata; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterHtmlChardata(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitHtmlChardata(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHtmlChardata(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HtmlChardataContext htmlChardata() {
		HtmlChardataContext _localctx = new HtmlChardataContext(Context, State);
		EnterRule(_localctx, 16, RULE_htmlChardata);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			_la = TokenStream.LA(1);
			if ( !(_la==SEA_WS || _la==HTML_TEXT) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttrValueContext : ParserRuleContext {
		public AttrValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attrValue; } }
	 
		public AttrValueContext() { }
		public virtual void CopyFrom(AttrValueContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DBL_QUOTE_STRINGContext : AttrValueContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_DQ_STR() { return GetToken(templateParser.TAG_DQ_STR, 0); }
		public DBL_QUOTE_STRINGContext(AttrValueContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterDBL_QUOTE_STRING(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitDBL_QUOTE_STRING(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDBL_QUOTE_STRING(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DBL_QUOTE_EXPRESSIONContext : AttrValueContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TAG_DBL_QUOTE() { return GetTokens(templateParser.TAG_DBL_QUOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_DBL_QUOTE(int i) {
			return GetToken(templateParser.TAG_DBL_QUOTE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Tag_expressionContext tag_expression() {
			return GetRuleContext<Tag_expressionContext>(0);
		}
		public DBL_QUOTE_EXPRESSIONContext(AttrValueContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterDBL_QUOTE_EXPRESSION(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitDBL_QUOTE_EXPRESSION(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDBL_QUOTE_EXPRESSION(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RAW_EXPRESSIONContext : AttrValueContext {
		[System.Diagnostics.DebuggerNonUserCode] public Tag_expressionContext tag_expression() {
			return GetRuleContext<Tag_expressionContext>(0);
		}
		public RAW_EXPRESSIONContext(AttrValueContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterRAW_EXPRESSION(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitRAW_EXPRESSION(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRAW_EXPRESSION(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttrValueContext attrValue() {
		AttrValueContext _localctx = new AttrValueContext(Context, State);
		EnterRule(_localctx, 18, RULE_attrValue);
		try {
			State = 113;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TAG_DBL_QUOTE:
				_localctx = new DBL_QUOTE_EXPRESSIONContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 107;
				Match(TAG_DBL_QUOTE);
				State = 108;
				tag_expression();
				State = 109;
				Match(TAG_DBL_QUOTE);
				}
				break;
			case TAG_EXP_OPEN:
				_localctx = new RAW_EXPRESSIONContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 111;
				tag_expression();
				}
				break;
			case TAG_DQ_STR:
				_localctx = new DBL_QUOTE_STRINGContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 112;
				Match(TAG_DQ_STR);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Tag_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAG_EXP_OPEN() { return GetToken(templateParser.TAG_EXP_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXP_CLOSE() { return GetToken(templateParser.EXP_CLOSE, 0); }
		public Tag_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tag_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterTag_expression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitTag_expression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTag_expression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Tag_expressionContext tag_expression() {
		Tag_expressionContext _localctx = new Tag_expressionContext(Context, State);
		EnterRule(_localctx, 20, RULE_tag_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115;
			Match(TAG_EXP_OPEN);
			State = 116;
			expr();
			State = 117;
			Match(EXP_CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveExprContext additiveExpr() {
			return GetRuleContext<AdditiveExprContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 22, RULE_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			additiveExpr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AdditiveExprContext : ParserRuleContext {
		public AdditiveExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additiveExpr; } }
	 
		public AdditiveExprContext() { }
		public virtual void CopyFrom(AdditiveExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ADDContext : AdditiveExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveExprContext additiveExpr() {
			return GetRuleContext<AdditiveExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(templateParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeExprContext multiplicativeExpr() {
			return GetRuleContext<MultiplicativeExprContext>(0);
		}
		public ADDContext(AdditiveExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterADD(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitADD(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitADD(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TO_MULTContext : AdditiveExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeExprContext multiplicativeExpr() {
			return GetRuleContext<MultiplicativeExprContext>(0);
		}
		public TO_MULTContext(AdditiveExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterTO_MULT(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitTO_MULT(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTO_MULT(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SUBTRACTContext : AdditiveExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveExprContext additiveExpr() {
			return GetRuleContext<AdditiveExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(templateParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeExprContext multiplicativeExpr() {
			return GetRuleContext<MultiplicativeExprContext>(0);
		}
		public SUBTRACTContext(AdditiveExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterSUBTRACT(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitSUBTRACT(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSUBTRACT(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AdditiveExprContext additiveExpr() {
		return additiveExpr(0);
	}

	private AdditiveExprContext additiveExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		AdditiveExprContext _localctx = new AdditiveExprContext(Context, _parentState);
		AdditiveExprContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_additiveExpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new TO_MULTContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 122;
			multiplicativeExpr(0);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 132;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 130;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
					case 1:
						{
						_localctx = new ADDContext(new AdditiveExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_additiveExpr);
						State = 124;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 125;
						Match(PLUS);
						State = 126;
						multiplicativeExpr(0);
						}
						break;
					case 2:
						{
						_localctx = new SUBTRACTContext(new AdditiveExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_additiveExpr);
						State = 127;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 128;
						Match(MINUS);
						State = 129;
						multiplicativeExpr(0);
						}
						break;
					}
					} 
				}
				State = 134;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class MultiplicativeExprContext : ParserRuleContext {
		public MultiplicativeExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplicativeExpr; } }
	 
		public MultiplicativeExprContext() { }
		public virtual void CopyFrom(MultiplicativeExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TO_UNARYContext : MultiplicativeExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public UnaryExprContext unaryExpr() {
			return GetRuleContext<UnaryExprContext>(0);
		}
		public TO_UNARYContext(MultiplicativeExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterTO_UNARY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitTO_UNARY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTO_UNARY(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MULTIPLYContext : MultiplicativeExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeExprContext multiplicativeExpr() {
			return GetRuleContext<MultiplicativeExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(templateParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnaryExprContext unaryExpr() {
			return GetRuleContext<UnaryExprContext>(0);
		}
		public MULTIPLYContext(MultiplicativeExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterMULTIPLY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitMULTIPLY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMULTIPLY(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DIVIDEContext : MultiplicativeExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeExprContext multiplicativeExpr() {
			return GetRuleContext<MultiplicativeExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIVIDE() { return GetToken(templateParser.DIVIDE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnaryExprContext unaryExpr() {
			return GetRuleContext<UnaryExprContext>(0);
		}
		public DIVIDEContext(MultiplicativeExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterDIVIDE(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitDIVIDE(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDIVIDE(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplicativeExprContext multiplicativeExpr() {
		return multiplicativeExpr(0);
	}

	private MultiplicativeExprContext multiplicativeExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		MultiplicativeExprContext _localctx = new MultiplicativeExprContext(Context, _parentState);
		MultiplicativeExprContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_multiplicativeExpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new TO_UNARYContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 136;
			unaryExpr();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 146;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 144;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
					case 1:
						{
						_localctx = new MULTIPLYContext(new MultiplicativeExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_multiplicativeExpr);
						State = 138;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 139;
						Match(MULT);
						State = 140;
						unaryExpr();
						}
						break;
					case 2:
						{
						_localctx = new DIVIDEContext(new MultiplicativeExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_multiplicativeExpr);
						State = 141;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 142;
						Match(DIVIDE);
						State = 143;
						unaryExpr();
						}
						break;
					}
					} 
				}
				State = 148;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class UnaryExprContext : ParserRuleContext {
		public UnaryExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpr; } }
	 
		public UnaryExprContext() { }
		public virtual void CopyFrom(UnaryExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TO_PRIMARYContext : UnaryExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public PrimaryExprContext primaryExpr() {
			return GetRuleContext<PrimaryExprContext>(0);
		}
		public TO_PRIMARYContext(UnaryExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterTO_PRIMARY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitTO_PRIMARY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTO_PRIMARY(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NEGATEContext : UnaryExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(templateParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnaryExprContext unaryExpr() {
			return GetRuleContext<UnaryExprContext>(0);
		}
		public NEGATEContext(UnaryExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterNEGATE(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitNEGATE(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNEGATE(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExprContext unaryExpr() {
		UnaryExprContext _localctx = new UnaryExprContext(Context, State);
		EnterRule(_localctx, 28, RULE_unaryExpr);
		try {
			State = 152;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MINUS:
				_localctx = new NEGATEContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 149;
				Match(MINUS);
				State = 150;
				unaryExpr();
				}
				break;
			case ID:
			case OPEN_PAREN:
			case INT:
			case REAL:
			case EXP_DQ_STR:
				_localctx = new TO_PRIMARYContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 151;
				primaryExpr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryExprContext : ParserRuleContext {
		public PrimaryExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primaryExpr; } }
	 
		public PrimaryExprContext() { }
		public virtual void CopyFrom(PrimaryExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CALLContext : PrimaryExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(templateParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_PAREN() { return GetToken(templateParser.OPEN_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_PAREN() { return GetToken(templateParser.CLOSE_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		public CALLContext(PrimaryExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterCALL(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitCALL(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCALL(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PARENSContext : PrimaryExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_PAREN() { return GetToken(templateParser.OPEN_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_PAREN() { return GetToken(templateParser.CLOSE_PAREN, 0); }
		public PARENSContext(PrimaryExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterPARENS(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitPARENS(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPARENS(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VARIABLEContext : PrimaryExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(templateParser.ID, 0); }
		public VARIABLEContext(PrimaryExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterVARIABLE(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitVARIABLE(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVARIABLE(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MAGIC_NUMBERContext : PrimaryExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public MAGIC_NUMBERContext(PrimaryExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterMAGIC_NUMBER(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitMAGIC_NUMBER(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMAGIC_NUMBER(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MAGIC_STRINGContext : PrimaryExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXP_DQ_STR() { return GetToken(templateParser.EXP_DQ_STR, 0); }
		public MAGIC_STRINGContext(PrimaryExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterMAGIC_STRING(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitMAGIC_STRING(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMAGIC_STRING(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryExprContext primaryExpr() {
		PrimaryExprContext _localctx = new PrimaryExprContext(Context, State);
		EnterRule(_localctx, 30, RULE_primaryExpr);
		int _la;
		try {
			State = 167;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				_localctx = new MAGIC_NUMBERContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 154;
				number();
				}
				break;
			case 2:
				_localctx = new MAGIC_STRINGContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 155;
				Match(EXP_DQ_STR);
				}
				break;
			case 3:
				_localctx = new VARIABLEContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 156;
				Match(ID);
				}
				break;
			case 4:
				_localctx = new CALLContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 157;
				Match(ID);
				State = 158;
				Match(OPEN_PAREN);
				State = 160;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 93913088L) != 0)) {
					{
					State = 159;
					argList();
					}
				}

				State = 162;
				Match(CLOSE_PAREN);
				}
				break;
			case 5:
				_localctx = new PARENSContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 163;
				Match(OPEN_PAREN);
				State = 164;
				expr();
				State = 165;
				Match(CLOSE_PAREN);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgListContext : ParserRuleContext {
		public ArgListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argList; } }
	 
		public ArgListContext() { }
		public virtual void CopyFrom(ArgListContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ARGSContext : ArgListContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(templateParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(templateParser.COMMA, i);
		}
		public ARGSContext(ArgListContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterARGS(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitARGS(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitARGS(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgListContext argList() {
		ArgListContext _localctx = new ArgListContext(Context, State);
		EnterRule(_localctx, 32, RULE_argList);
		int _la;
		try {
			_localctx = new ARGSContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			expr();
			State = 174;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 170;
				Match(COMMA);
				State = 171;
				expr();
				}
				}
				State = 176;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(templateParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REAL() { return GetToken(templateParser.REAL, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.EnterNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ItemplateParserListener typedListener = listener as ItemplateParserListener;
			if (typedListener != null) typedListener.ExitNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItemplateParserVisitor<TResult> typedVisitor = visitor as ItemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 34, RULE_number);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 177;
			_la = TokenStream.LA(1);
			if ( !(_la==INT || _la==REAL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 12: return additiveExpr_sempred((AdditiveExprContext)_localctx, predIndex);
		case 13: return multiplicativeExpr_sempred((MultiplicativeExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool additiveExpr_sempred(AdditiveExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		case 1: return Precpred(Context, 2);
		}
		return true;
	}
	private bool multiplicativeExpr_sempred(MultiplicativeExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 2: return Precpred(Context, 3);
		case 3: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,28,180,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,1,0,5,0,38,8,0,10,0,12,0,41,9,0,1,0,1,0,
		1,1,5,1,46,8,1,10,1,12,1,49,9,1,1,1,1,1,5,1,53,8,1,10,1,12,1,56,9,1,1,
		2,1,2,1,3,1,3,1,4,1,4,1,4,5,4,65,8,4,10,4,12,4,68,9,4,1,4,1,4,1,4,1,4,
		1,4,1,4,1,4,3,4,77,8,4,1,4,3,4,80,8,4,1,5,3,5,83,8,5,1,5,1,5,3,5,87,8,
		5,1,5,3,5,90,8,5,5,5,92,8,5,10,5,12,5,95,9,5,1,6,1,6,1,6,1,6,1,7,1,7,1,
		7,3,7,104,8,7,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,3,9,114,8,9,1,10,1,10,1,
		10,1,10,1,11,1,11,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,5,12,131,
		8,12,10,12,12,12,134,9,12,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,
		5,13,145,8,13,10,13,12,13,148,9,13,1,14,1,14,1,14,3,14,153,8,14,1,15,1,
		15,1,15,1,15,1,15,1,15,3,15,161,8,15,1,15,1,15,1,15,1,15,1,15,3,15,168,
		8,15,1,16,1,16,1,16,5,16,173,8,16,10,16,12,16,176,9,16,1,17,1,17,1,17,
		0,2,24,26,18,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,0,2,2,0,
		1,1,3,3,1,0,23,24,185,0,39,1,0,0,0,2,47,1,0,0,0,4,57,1,0,0,0,6,59,1,0,
		0,0,8,61,1,0,0,0,10,82,1,0,0,0,12,96,1,0,0,0,14,100,1,0,0,0,16,105,1,0,
		0,0,18,113,1,0,0,0,20,115,1,0,0,0,22,119,1,0,0,0,24,121,1,0,0,0,26,135,
		1,0,0,0,28,152,1,0,0,0,30,167,1,0,0,0,32,169,1,0,0,0,34,177,1,0,0,0,36,
		38,3,2,1,0,37,36,1,0,0,0,38,41,1,0,0,0,39,37,1,0,0,0,39,40,1,0,0,0,40,
		42,1,0,0,0,41,39,1,0,0,0,42,43,5,0,0,1,43,1,1,0,0,0,44,46,3,4,2,0,45,44,
		1,0,0,0,46,49,1,0,0,0,47,45,1,0,0,0,47,48,1,0,0,0,48,50,1,0,0,0,49,47,
		1,0,0,0,50,54,3,8,4,0,51,53,3,4,2,0,52,51,1,0,0,0,53,56,1,0,0,0,54,52,
		1,0,0,0,54,55,1,0,0,0,55,3,1,0,0,0,56,54,1,0,0,0,57,58,5,1,0,0,58,5,1,
		0,0,0,59,60,5,9,0,0,60,7,1,0,0,0,61,62,5,2,0,0,62,66,3,6,3,0,63,65,3,14,
		7,0,64,63,1,0,0,0,65,68,1,0,0,0,66,64,1,0,0,0,66,67,1,0,0,0,67,79,1,0,
		0,0,68,66,1,0,0,0,69,76,5,5,0,0,70,71,3,10,5,0,71,72,5,2,0,0,72,73,5,7,
		0,0,73,74,5,9,0,0,74,75,5,5,0,0,75,77,1,0,0,0,76,70,1,0,0,0,76,77,1,0,
		0,0,77,80,1,0,0,0,78,80,5,6,0,0,79,69,1,0,0,0,79,78,1,0,0,0,80,9,1,0,0,
		0,81,83,3,16,8,0,82,81,1,0,0,0,82,83,1,0,0,0,83,93,1,0,0,0,84,87,3,8,4,
		0,85,87,3,12,6,0,86,84,1,0,0,0,86,85,1,0,0,0,87,89,1,0,0,0,88,90,3,16,
		8,0,89,88,1,0,0,0,89,90,1,0,0,0,90,92,1,0,0,0,91,86,1,0,0,0,92,95,1,0,
		0,0,93,91,1,0,0,0,93,94,1,0,0,0,94,11,1,0,0,0,95,93,1,0,0,0,96,97,5,4,
		0,0,97,98,3,22,11,0,98,99,5,14,0,0,99,13,1,0,0,0,100,103,3,6,3,0,101,102,
		5,8,0,0,102,104,3,18,9,0,103,101,1,0,0,0,103,104,1,0,0,0,104,15,1,0,0,
		0,105,106,7,0,0,0,106,17,1,0,0,0,107,108,5,11,0,0,108,109,3,20,10,0,109,
		110,5,11,0,0,110,114,1,0,0,0,111,114,3,20,10,0,112,114,5,12,0,0,113,107,
		1,0,0,0,113,111,1,0,0,0,113,112,1,0,0,0,114,19,1,0,0,0,115,116,5,13,0,
		0,116,117,3,22,11,0,117,118,5,14,0,0,118,21,1,0,0,0,119,120,3,24,12,0,
		120,23,1,0,0,0,121,122,6,12,-1,0,122,123,3,26,13,0,123,132,1,0,0,0,124,
		125,10,3,0,0,125,126,5,15,0,0,126,131,3,26,13,0,127,128,10,2,0,0,128,129,
		5,16,0,0,129,131,3,26,13,0,130,124,1,0,0,0,130,127,1,0,0,0,131,134,1,0,
		0,0,132,130,1,0,0,0,132,133,1,0,0,0,133,25,1,0,0,0,134,132,1,0,0,0,135,
		136,6,13,-1,0,136,137,3,28,14,0,137,146,1,0,0,0,138,139,10,3,0,0,139,140,
		5,17,0,0,140,145,3,28,14,0,141,142,10,2,0,0,142,143,5,18,0,0,143,145,3,
		28,14,0,144,138,1,0,0,0,144,141,1,0,0,0,145,148,1,0,0,0,146,144,1,0,0,
		0,146,147,1,0,0,0,147,27,1,0,0,0,148,146,1,0,0,0,149,150,5,16,0,0,150,
		153,3,28,14,0,151,153,3,30,15,0,152,149,1,0,0,0,152,151,1,0,0,0,153,29,
		1,0,0,0,154,168,3,34,17,0,155,168,5,26,0,0,156,168,5,19,0,0,157,158,5,
		19,0,0,158,160,5,20,0,0,159,161,3,32,16,0,160,159,1,0,0,0,160,161,1,0,
		0,0,161,162,1,0,0,0,162,168,5,21,0,0,163,164,5,20,0,0,164,165,3,22,11,
		0,165,166,5,21,0,0,166,168,1,0,0,0,167,154,1,0,0,0,167,155,1,0,0,0,167,
		156,1,0,0,0,167,157,1,0,0,0,167,163,1,0,0,0,168,31,1,0,0,0,169,174,3,22,
		11,0,170,171,5,22,0,0,171,173,3,22,11,0,172,170,1,0,0,0,173,176,1,0,0,
		0,174,172,1,0,0,0,174,175,1,0,0,0,175,33,1,0,0,0,176,174,1,0,0,0,177,178,
		7,1,0,0,178,35,1,0,0,0,20,39,47,54,66,76,79,82,86,89,93,103,113,130,132,
		144,146,152,160,167,174
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace dhll.v1
